### ISSUE TITLE
Update clang-format rules

### ISSUE THREAD

**Issue by Gashmob** [Fil-Language/filc#44]
I'm not very happy with what clang-format do. I should try to fine tune them to have exactly what I want

https://clang.llvm.org/docs/ClangFormatStyleOptions.html

```yml
---
BasedOnStyle: LLVM
AlignAfterOpenBracket: BlockIndent
AlignArrayOfStructures: Left
AlignConsecutiveAssignments:
  Enabled: true
  AcrossComments: true
AlignConsecutiveBitFields:
  Enabled: true
  AcrossComments: true
AlignConsecutiveMacros:
  Enabled: true
  AcrossComments: true
AlignConsecutiveShortCaseStatements:
  Enabled: true
  AcrossComments: true
AlignEscapedNewlines: LeftWithLastLine
AlignOperands: AlignAfterOperator
AllowShortBlocksOnASingleLine: Empty
AllowShortFunctionsOnASingleLine: Empty
AllowShortIfStatementsOnASingleLine: WithoutElse
AllowShortLambdasOnASingleLine: Empty
AlwaysBreakBeforeMultilineStrings: true
BinPackArguments: false
BinPackParameters: false
BreakBeforeBinaryOperators: All
BreakTemplateDeclarations: Yes
ColumnLimit: 120
IncludeBlocks: Regroup
IndentWidth: 4
InsertBraces: true
InsertNewlineAtEOF: true
InsertTrailingCommas: Wrapped
LineEnding: LF
RemoveParentheses: MultipleParentheses
RemoveSemicolon: true
SpaceAfterCStyleCast: true
SpaceAfterLogicalNot: true
SpaceAfterTemplateKeyword: false
SpaceBeforeCtorInitializerColon: false
SpacesInContainerLiterals: false
Standard: c++17
TabWidth: 4
BracedInitializerIndentWidth: 2

```
