### ISSUE TITLE
Rework of filc entry point

### ISSUE THREAD

**Issue by Gashmob** [Fil-Language/Filc#81]
Currently `filc` takes all source files and compile them. The goal of this issue is to rework that.

Instead of taking files and options, it will take commands and will work with a config file (like npm)

### Config file

- [x] It will be a `module.yml` file generated by `filc` and in this format :

```yml
name: "<project name>"
description: "<project short description>"
version: "<project version>"
entrypoint: "<path to main source file>"
namespaces:
    name.of.namespace: "<path to namespace>"
```

### Commands

Here it list all available commands :

- [x] `init` -> interactive command to init a project (it creates `module.yml` and the entrypoint file)
- [x] `build` -> build the project conforming to config file

### Others tasks

- [x] At the end, remove cxxopts.hpp and OptionsParser
